name: Merge main into quartz

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rebase-quartz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>@users.noreply.github.com"

      - name: Merge main into quartz
        run: |
          git switch quartz
          git merge origin/main --no-edit

      - name: Push rebased quartz
        run: |
          git push --force